GET http://localhost:3000/api/v1/users

###
POST http://localhost:3000/api/v1/users
content-type: application/json

{
  "user" : {
    "name": "user",
    "email": "user@mail.com",
    "password": "password",
    "password_confirmation": "password"
  }
}